project:
  type: website
  output-dir: _site
  render:
    - "index.qmd"
    - "about.qmd"
    - "modules/**/*.qmd"
    - "glossary/**/*.qmd"
    - "posts/**/*.qmd"
    - "resources/**/*.qmd"

website:
  title: "The Curious Notebook"
  page-navigation: true
  search: true
  navbar:
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Modules"
        href: modules/index.qmd
        menu:
          - text: "Dynamics That Compute"
            href: modules/dynamics_that_compute/index.qmd
      - text: "Posts"
        href: posts/index.qmd
      - text: "About"
        href: about.qmd

  sidebar:
    - title: "Dynamics That Compute"
      collapse-level: 0
      contents:
        - text: "Overview"
          href: modules/dynamics_that_compute/index.qmd
        - section: "Experiments"
          contents:
            - auto: "modules/dynamics_that_compute/*/index.qmd"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    include-after-body: _includes/article-navigation.html
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
